### ISSUE TITLE
Dark mode compatibility

### ISSUE THREAD

**Issue by mwaldmueller** [Thomas-Gelf/icingaweb2-module-iet#6]
IET Module should support dark mode.

![iet_dark_mode](https://user-images.githubusercontent.com/3973350/192697925-5a2593ec-2eae-47b3-a1af-b744df25f27a.png)

**Environment**
IET Module: v0.9.0
Incubator Module: v0.18.0
Icinga Web: 2.10.3

**Comment by mwaldmueller** [comment]
ref/NC/763312

**Comment by Thomas-Gelf** [comment]
![grafik](https://user-images.githubusercontent.com/553008/194223757-396b4451-bdfd-4982-ad9c-62d57d5bad29.png)

This should have been fixed a while ago in a recent Incubator module (and definitively in 0.18), combined with cc68010 (which switched to a related base class) this resolves this issue
